### ISSUE TITLE
Cannot wake screen from sleep

### ISSUE THREAD

**Issue by nicoolaro** [ChefKissInc/NootedRed#207]
### macOS Version

Ventura

### What is your CPU's model?

Ryzen 5 5625u

### Please describe the behaviour in detail.

Everything else works great , followed guide.\
But Screen goes to sleep but can't wake up , it seems that the system is up as i can hear the sound but the screen stays black.

Lenovo Thinkpad v15 g4 with Ryzen 5 5625u 

### What should've happened instead?

Wake from sleep

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by nisel11** [comment]
I confirm this problem with Ryzen 5 3550H and Vega 8, but I also want to say that I have to wait more than an hour for this to happen, and also that this problem does not occur if you close the laptop lid instead of just pressing the sleep button

**Comment by VisualEhrmanntraut** [comment]
Issues with sleep are unlikely to be caused by NootedRed, as SMU code has been ported from the Adrenaline drivers, even if the screen doesn't wake up. It is likely caused by another component not waking up, like USB. If you can hard prove that it is caused by the graphics (not with just a log that says something along the lines of "suspected bundle IOGraphicsFamily", as there's no guarantee the guess made is correct), then I will save it as something to investigate at a later date. For Hackintosh help, ask in the Telegram supergroup linked in our site.
