### ISSUE TITLE
Rendering issues possible caused by nootedred 

### ISSUE THREAD

**Issue by rishthedev** [ChefKissInc/NootedRed#243]
### macOS Version

Sonoma

### What is your CPU's model?

Ryzen 7 5700G 

### Please describe the behaviour in detail.

![IMG_20240330_195232](https://github.com/ChefKissInc/NootedRed/assets/163291651/c78d9828-6774-44d1-8c2d-1df39b9f23ba)
Randomly a red rectangle appears that covers the whole of safari. It will dissappear after i reload but may have the issue again. 

### What should've happened instead?

Not to have render issues on safari 

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by jpsaturnino** [comment]
This can be caused by insufficient VRAM size, look at https://chefkissinc.github.io/nred#prerequisites. You can do this by updating your bios, search by `UMA mode` and force to at least 1gb depending on your available memory.

![Screenshot 2024-04-05 at 21 03 00](https://github.com/ChefKissInc/NootedRed/assets/47997386/45d6dc23-6a41-4711-8732-cbd0bf44d5eb)

**Comment by Dummy-Soft** [comment]
Disabel hardware acceleration in the browser

**Comment by VisualEhrmanntraut** [comment]
Here are the most common things to look out for:
- Outdated version of this kext.
- Conflicts with other kexts (e.g. WhateverGreen).
- Issues caused by other kexts like memory corruption (e.g. AirportItlwm).
- Using cheap hacks like kext/library downgrades (e.g. OCLP, BFixup).
- Duplicate kexts.
- Malformed config.plist caused by configurator software (OCAT, OCC, etc).
- Lack of TSC synchronisation (use AmdTscSync).
- Badly configured TSC synchronisation (set IOCPUNumber in the Info.plist to number of threads minus one for macOS 11 and older, 0 for anything newer).
- Outdated macOS minor version (e.g. macOS 11.0.0 instead of latest).
- Using beta versions of macOS.

**Comment by VisualEhrmanntraut** [comment]
Timed out waiting for response.
